### PR TITLE
Added compatibility with hover mode

### PR DESCRIPTION
**Pull request by nichhk**
Created class ParameterPacket that is sent whenever the toggle button "hover" is pressed. The quadcopter will shut off if you try to enter hover mode while grounded.

### CODE REVIEW

**Comment by ataffanel** [comment]
Hi @nichhk, I have not looked at the pull request in detail but I have just a comment:

> The quadcopter will shut off if you try to enter hover mode while grounded.

This looks like a firmware bug in the first batch of Crazyflie 2.0 and it has been fixed in a firmware update, have you updated your firmware?

**Comment by nichhk** [comment]
Hi @ataffanel, yes, I had flashed the firmware that said that that issue was fixed. It still shuts off though. Any thoughts?

**Comment by fredg02** [comment]
Hi @nichhk,
Thanks for your pull request. I really like the idea of your ParameterPacket class, even though I think it should be a more general class that takes the following parameters:
- parameter ID
- parameter value to set

I'm a bit unsure if it's a save way to toggle the hover mode with an onscreen button (I still have to test it). The original idea was that the user has to keep pressing a gamepad controller button to stay in hover mode (see http://wiki.bitcraze.se/projects:crazyflie:firmware:altitude_hold).

Apart from that, I'm very sorry, but I can't merge this pull request. There are too many changes (white spaces, indentation, added comments, removed license, etc) and a merge commit that don't seem to be relevant to the actual enhancement.

Based on your pull request I have implemented a hover mode that can be assigned to a gamepad button (as a first step). Once I have confirmed that a toggle-onscreen-button mode is reasonably save, this could also be implemented.

**Comment by nichhk** [comment]
Hey @fredg02, I wanted to use an onscreen button because I couldn't connect an external controller to my phone. Why do you think it might be unsafe? One thing that I was worried about was the packet not being transmitted since every other packet is ignored in BleLink's send() method.

I understand why you can't merge it, no worries. I still need to learn how to use GitHub and make proper pull requests. I hope this pull request helped though. 

If I want to continue contributing, should I just scrap my current branch and start fresh from the main branch?

**Comment by fredg02** [comment]
Hey @nichhk,
The onscreen controls give no feedback, so you might miss the button. That was my reason for the concern. 
I have not tested it with Bluetooth LE yet, but that's a good point.

Yes, I'd recommend to start fresh. Have a look at the contributing guide and the tutorial. 
 - https://github.com/bitcraze/crazyflie-android-client/blob/master/CONTRIBUTING.md
 - http://www.thinkful.com/learn/github-pull-request-tutorial/

**Comment by fredg02** [comment]
Hey @nichhk, I tested your toggle-onscreen mode. It worked alright with the CF1 and the Crazyradio. When testing the CF2 and BLE I managed to break off one motor mount during a crash, because the CF fell out of the sky. The motor mount was easily replaceable, but it confirmed my concerns. I consider the combination CF2, BLE and hover mode with toggle-onscreen not save (yet). The hover mode of the CF2 seems to be worse than the one of CF1, BLE probably adds little bit of latency and the toggle-onscreen button is hard to reach when you're trying to control roll&pitch at the same time (Mode 3).
So for now, I will only support the hover mode with a gamepad.

You were right about BLE: there is a problem with the hover mode not working correctly when using the "keep-the-button-pressed" mode.

**Pull request closed without merging**
